# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4GGBlu6MYRi5l49C8emcGWmFBttnE_3
"""

# Step 6: Test Script

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image

# Load the trained model
loaded_model = tf.keras.models.load_model('/content/drive/MyDrive/CSE465/model.h5')  # Adjust the path if necessary

# Test the model on new images
test_image_path = "/content/drive/MyDrive/CSE465/Mango/Anthracnose/20211008_124249 (Custom).jpg"  # Path to the test image (replace with your test image path)
test_image = image.load_img(test_image_path, target_size=(224, 224))  # Resize to match model input size
test_image_array = image.img_to_array(test_image)  # Convert image to array
test_image_array = np.expand_dims(test_image_array, axis=0)  # Add batch dimension
test_image_array /= 255.0  # Rescale the image (same preprocessing used during training)

# Predict using the model
prediction = loaded_model.predict(test_image_array)  # Get predictions
predicted_class = np.argmax(prediction, axis=1)  # Get the class with the highest probability

# Display the result
print(f"Predicted class: {predicted_class[0]}")  # Print the predicted class