# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4GGBlu6MYRi5l49C8emcGWmFBttnE_3
"""

from tensorflow.keras.preprocessing import image

model.save('/content/final_model.h5')  # Save the trained model

# Load model and test on one image
loaded_model = tf.keras.models.load_model('/content/final_model.h5')

test_image_path = "/content/drive/MyDrive/CSE465/Mango/Anthracnose/20211008_124249 (Custom).jpg"
test_image = image.load_img(test_image_path, target_size=(224, 224))
test_image_array = image.img_to_array(test_image)
test_image_array = np.expand_dims(test_image_array, axis=0)
test_image_array /= 255.0

prediction = loaded_model.predict(test_image_array)
predicted_class = np.argmax(prediction, axis=1)

print(f"Predicted class: {predicted_class[0]}")